// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgIz34AWIaHvd-8PYGu_obCmre9AbApwc',
    appId: '1:858421664488:web:9cee1c758705cbbfdc875d',
    messagingSenderId: '858421664488',
    projectId: 'playmate-cd477',
    authDomain: 'playmate-cd477.firebaseapp.com',
    storageBucket: 'playmate-cd477.firebasestorage.app',
    measurementId: 'G-XEN73Y7XES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIye899obha-RLWQhinDoBghs0Jnoi8To',
    appId: '1:858421664488:android:666211419392931cdc875d',
    messagingSenderId: '858421664488',
    projectId: 'playmate-cd477',
    storageBucket: 'playmate-cd477.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ywlunEZpp6TOhD_Bm1-jzm5UYlbcD88',
    appId: '1:858421664488:ios:5461a0d519b4b0f8dc875d',
    messagingSenderId: '858421664488',
    projectId: 'playmate-cd477',
    storageBucket: 'playmate-cd477.firebasestorage.app',
    iosBundleId: 'com.example.playmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7ywlunEZpp6TOhD_Bm1-jzm5UYlbcD88',
    appId: '1:858421664488:ios:5461a0d519b4b0f8dc875d',
    messagingSenderId: '858421664488',
    projectId: 'playmate-cd477',
    storageBucket: 'playmate-cd477.firebasestorage.app',
    iosBundleId: 'com.example.playmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgIz34AWIaHvd-8PYGu_obCmre9AbApwc',
    appId: '1:858421664488:web:099cc5dfa151cbd5dc875d',
    messagingSenderId: '858421664488',
    projectId: 'playmate-cd477',
    authDomain: 'playmate-cd477.firebaseapp.com',
    storageBucket: 'playmate-cd477.firebasestorage.app',
    measurementId: 'G-12GRFNDNW1',
  );

}